import fs from 'fs';
import path from 'path';

const distDir = './frontend/dist';
const assetsDir = path.join(distDir, 'assets');
const outputFile = './src/assets.js';

// Read files
const html = fs.readFileSync(path.join(distDir, 'index.html'), 'utf8');
const jsFiles = fs.readdirSync(assetsDir).filter(f => f.endsWith('.js'));
const cssFiles = fs.readdirSync(assetsDir).filter(f => f.endsWith('.css'));

const js = fs.readFileSync(path.join(assetsDir, jsFiles[0]), 'utf8');
const css = fs.readFileSync(path.join(assetsDir, cssFiles[0]), 'utf8');

// Generate JS module
const output = `// Auto-generated by build-assets.js
export const indexHtml = ${JSON.stringify(html)};
export const indexJs = ${JSON.stringify(js)};
export const indexCss = ${JSON.stringify(css)};
export const jsPath = ${JSON.stringify('/assets/' + jsFiles[0])};
export const cssPath = ${JSON.stringify('/assets/' + cssFiles[0])};
`;

fs.writeFileSync(outputFile, output);
console.log('Assets embedded in src/assets.js');
